CREATE OR REPLACE FUNCTION update_balance()
  RETURNS trigger AS
$BODY$ 
	BEGIN
		UPDATE CART SET BALANCE = BALANCE + (NEW.QUANTITY * (SELECT PRICE FROM PRODUCT WHERE PRODUCTID=NEW.PRODUCTID)) WHERE CART.CARTID=NEW.CARTID;
		return new;
	END;
	$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
  
 CREATE OR REPLACE FUNCTION repeated_product()
  RETURNS trigger AS
$BODY$ 
	BEGIN
		IF(repeated (NEW.name,NEW.establishmentid)>0)THEN
		 RAISE EXCEPTION 'products cant be repeated';
	END IF;
	return new;
	END;
	$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
  
		
	
	
