CREATE OR REPLACE FUNCTION update_balance()
  RETURNS trigger AS
$BODY$ 
	BEGIN
		UPDATE CART SET BALANCE = BALANCE + (NEW.QUANTITY * (SELECT PRICE FROM PRODUCT WHERE PRODUCTID=NEW.PRODUCTID)) WHERE CART.CARTID=NEW.CARTID;
		return new;
	END;
	$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;